management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: '/'
  server:
    port: 8081
---
spring:
  profiles: dev
server:
  port: 8000
management:
  server:
    port: 8001
---
spring:
  profiles: test
server:
  port: 9000
management:
  server:
    port: 9001